services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow.Dockerfile
    environment:
      BACKEND_STORE_URI: postgresql://mlflow:mlflow@postgres:5432/mlflow
      ARTIFACT_ROOT: /mlflow_artifacts
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - mlflow_artifacts:/mlflow_artifacts
    depends_on:
      - postgres

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./config.yaml:/app/config.yaml:ro
      - ./src:/app/src
    depends_on:
      - mlflow

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__RBAC: "true"
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./config.yaml:/opt/airflow/config.yaml:ro
    depends_on:
      - mlflow

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    command: ["airflow", "scheduler"]
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./config.yaml:/opt/airflow/config.yaml:ro
    depends_on:
      - airflow-webserver

volumes:
  pgdata:
  mlflow_artifacts:
