[project]
name = "mlops-final-project"
version = "0.1.0"
requires-python = ">=3.10"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
