name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
          pre-commit install
      - name: Lint (pre-commit)
        run: pre-commit run --all-files
      - name: Smoke pipeline
        env:
          MLFLOW_TRACKING_URI: "file:./mlruns"
        run: |
          python -m src.data.get_data
          python -m src.features.transform
          python -m src.models.train
          python -m src.models.validate
          python -m src.data.simulate_drift
          python -m src.monitoring.generate_drift
      - name: Tests
        run: pytest -q
